packages:
  - .
  - packages/*
  - apps/*

allowBuilds:
  core-js: true
  esbuild: true
  workerd: true

patchedDependencies:
  '@react-native/gradle-plugin@0.87.1': patches/@react-native__gradle-plugin@0.87.1.patch

publicHoistPattern:
  - 'metro'
  - 'metro-*'
  - '@expo/metro-config'
  - '@expo/cli'
  - '@vxrn/vite-plugin-metro'
  - 'babel-preset-expo'
  - 'babel-plugin-module-resolver'
